// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: proto/fractal.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FractalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          int32                  `protobuf:"varint,1,opt,name=kind,proto3" json:"kind,omitempty"`
	MaxIterations int32                  `protobuf:"varint,2,opt,name=max_iterations,json=maxIterations,proto3" json:"max_iterations,omitempty"`
	XMin          float64                `protobuf:"fixed64,3,opt,name=x_min,json=xMin,proto3" json:"x_min,omitempty"`
	XMax          float64                `protobuf:"fixed64,4,opt,name=x_max,json=xMax,proto3" json:"x_max,omitempty"`
	YMin          float64                `protobuf:"fixed64,5,opt,name=y_min,json=yMin,proto3" json:"y_min,omitempty"`
	YMax          float64                `protobuf:"fixed64,6,opt,name=y_max,json=yMax,proto3" json:"y_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FractalRequest) Reset() {
	*x = FractalRequest{}
	mi := &file_proto_fractal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FractalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FractalRequest) ProtoMessage() {}

func (x *FractalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fractal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FractalRequest.ProtoReflect.Descriptor instead.
func (*FractalRequest) Descriptor() ([]byte, []int) {
	return file_proto_fractal_proto_rawDescGZIP(), []int{0}
}

func (x *FractalRequest) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *FractalRequest) GetMaxIterations() int32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

func (x *FractalRequest) GetXMin() float64 {
	if x != nil {
		return x.XMin
	}
	return 0
}

func (x *FractalRequest) GetXMax() float64 {
	if x != nil {
		return x.XMax
	}
	return 0
}

func (x *FractalRequest) GetYMin() float64 {
	if x != nil {
		return x.YMin
	}
	return 0
}

func (x *FractalRequest) GetYMax() float64 {
	if x != nil {
		return x.YMax
	}
	return 0
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Intensity     int32                  `protobuf:"varint,3,opt,name=intensity,proto3" json:"intensity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_proto_fractal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fractal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_proto_fractal_proto_rawDescGZIP(), []int{1}
}

func (x *Point) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Point) GetIntensity() int32 {
	if x != nil {
		return x.Intensity
	}
	return 0
}

type FractalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*Point               `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FractalResponse) Reset() {
	*x = FractalResponse{}
	mi := &file_proto_fractal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FractalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FractalResponse) ProtoMessage() {}

func (x *FractalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fractal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FractalResponse.ProtoReflect.Descriptor instead.
func (*FractalResponse) Descriptor() ([]byte, []int) {
	return file_proto_fractal_proto_rawDescGZIP(), []int{2}
}

func (x *FractalResponse) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

var File_proto_fractal_proto protoreflect.FileDescriptor

const file_proto_fractal_proto_rawDesc = "" +
	"\n" +
	"\x13proto/fractal.proto\x12\afractal\"\x9f\x01\n" +
	"\x0eFractalRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\x05R\x04kind\x12%\n" +
	"\x0emax_iterations\x18\x02 \x01(\x05R\rmaxIterations\x12\x13\n" +
	"\x05x_min\x18\x03 \x01(\x01R\x04xMin\x12\x13\n" +
	"\x05x_max\x18\x04 \x01(\x01R\x04xMax\x12\x13\n" +
	"\x05y_min\x18\x05 \x01(\x01R\x04yMin\x12\x13\n" +
	"\x05y_max\x18\x06 \x01(\x01R\x04yMax\"A\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\x1c\n" +
	"\tintensity\x18\x03 \x01(\x05R\tintensity\"9\n" +
	"\x0fFractalResponse\x12&\n" +
	"\x06points\x18\x01 \x03(\v2\x0e.fractal.PointR\x06points2Q\n" +
	"\x0eFractalService\x12?\n" +
	"\n" +
	"GetFractal\x12\x17.fractal.FractalRequest\x1a\x18.fractal.FractalResponseB\x19Z\x17go-ping-api/pkg/grpc/pbb\x06proto3"

var (
	file_proto_fractal_proto_rawDescOnce sync.Once
	file_proto_fractal_proto_rawDescData []byte
)

func file_proto_fractal_proto_rawDescGZIP() []byte {
	file_proto_fractal_proto_rawDescOnce.Do(func() {
		file_proto_fractal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fractal_proto_rawDesc), len(file_proto_fractal_proto_rawDesc)))
	})
	return file_proto_fractal_proto_rawDescData
}

var file_proto_fractal_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_fractal_proto_goTypes = []any{
	(*FractalRequest)(nil),  // 0: fractal.FractalRequest
	(*Point)(nil),           // 1: fractal.Point
	(*FractalResponse)(nil), // 2: fractal.FractalResponse
}
var file_proto_fractal_proto_depIdxs = []int32{
	1, // 0: fractal.FractalResponse.points:type_name -> fractal.Point
	0, // 1: fractal.FractalService.GetFractal:input_type -> fractal.FractalRequest
	2, // 2: fractal.FractalService.GetFractal:output_type -> fractal.FractalResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_fractal_proto_init() }
func file_proto_fractal_proto_init() {
	if File_proto_fractal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fractal_proto_rawDesc), len(file_proto_fractal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fractal_proto_goTypes,
		DependencyIndexes: file_proto_fractal_proto_depIdxs,
		MessageInfos:      file_proto_fractal_proto_msgTypes,
	}.Build()
	File_proto_fractal_proto = out.File
	file_proto_fractal_proto_goTypes = nil
	file_proto_fractal_proto_depIdxs = nil
}
