// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/fractal.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FractalService_GetFractal_FullMethodName = "/fractal.FractalService/GetFractal"
)

// FractalServiceClient is the client API for FractalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FractalServiceClient interface {
	GetFractal(ctx context.Context, in *FractalRequest, opts ...grpc.CallOption) (*FractalResponse, error)
}

type fractalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFractalServiceClient(cc grpc.ClientConnInterface) FractalServiceClient {
	return &fractalServiceClient{cc}
}

func (c *fractalServiceClient) GetFractal(ctx context.Context, in *FractalRequest, opts ...grpc.CallOption) (*FractalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FractalResponse)
	err := c.cc.Invoke(ctx, FractalService_GetFractal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FractalServiceServer is the server API for FractalService service.
// All implementations must embed UnimplementedFractalServiceServer
// for forward compatibility.
type FractalServiceServer interface {
	GetFractal(context.Context, *FractalRequest) (*FractalResponse, error)
	mustEmbedUnimplementedFractalServiceServer()
}

// UnimplementedFractalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFractalServiceServer struct{}

func (UnimplementedFractalServiceServer) GetFractal(context.Context, *FractalRequest) (*FractalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFractal not implemented")
}
func (UnimplementedFractalServiceServer) mustEmbedUnimplementedFractalServiceServer() {}
func (UnimplementedFractalServiceServer) testEmbeddedByValue()                        {}

// UnsafeFractalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FractalServiceServer will
// result in compilation errors.
type UnsafeFractalServiceServer interface {
	mustEmbedUnimplementedFractalServiceServer()
}

func RegisterFractalServiceServer(s grpc.ServiceRegistrar, srv FractalServiceServer) {
	// If the following call panics, it indicates UnimplementedFractalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FractalService_ServiceDesc, srv)
}

func _FractalService_GetFractal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FractalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FractalServiceServer).GetFractal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FractalService_GetFractal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FractalServiceServer).GetFractal(ctx, req.(*FractalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FractalService_ServiceDesc is the grpc.ServiceDesc for FractalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FractalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fractal.FractalService",
	HandlerType: (*FractalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFractal",
			Handler:    _FractalService_GetFractal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fractal.proto",
}
